name: Build 32-bit and 64-bit Windows Dynamic Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install mingw-w64 for cross-compilation
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64

    - name: Create combined source file
      run: |
      echo '#include "Tofile.c"' > all_functions.c
      for file in *.c; do
        if [ "$file" != "all_functions.c" ]; then
        echo "#include \"$file\"" >> all_functions.c
        fi
      done

    - name: Build 32-bit dynamic libraries
      run: |
        for file in *.c; do
          base_name=$(basename "$file" .c)
          i686-w64-mingw32-gcc -shared -static -O3 -fPIC -o "${base_name}32.dll" "$file"
        done
        i686-w64-mingw32-gcc -shared -static -O3 -fPIC -o "all_functions32.dll" all_functions.c

    - name: Build 64-bit dynamic libraries
      run: |
        for file in *.c; do
          base_name=$(basename "$file" .c)
          x86_64-w64-mingw32-gcc -shared -static -O3 -fPIC -o "${base_name}64.dll" "$file"
        done
        x86_64-w64-mingw32-gcc -shared -static -O3 -fPIC -o "all_functions64.dll" all_functions.c

    - name: Get current Git hash and time
      id: get_info
      run: |
        echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "CURRENT_TIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Upload built libraries
      uses: actions/upload-artifact@v2
      with:
        name: Data2Text_LabVIEW-${{ env.GIT_HASH }}-${{ env.CURRENT_TIME }}
        path: |
          *32.dll
          *64.dll
