name: Build DLL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install MinGW 32-bit
      run: |
        choco install mingw --params "/InstallDir:C:\mingw32 /32bit" -y
        echo "C:\mingw32\bin" >> $env:GITHUB_PATH
        echo "C:\mingw32\bin" >> $env:Path
        refreshenv

    - name: Verify MinGW installation
      run: |
        gcc --version
        where gcc

    - name: Build 32-bit DLL
      shell: cmd
      run: |
        gcc -shared -o ToText_32.dll -m32 ToText.c

    - name: Upload DLL
      uses: actions/upload-artifact@v2
      with:
        name: dll-files
        path: ./ToText_32.dll
