name: Build DLL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2016

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install MinGW 32-bit
      run: |
        choco install mingw -y
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw32\bin" >> $env:GITHUB_PATH
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw32\bin" >> $env:Path
        refreshenv

    - name: Verify MinGW installation
      run: |
        C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw32\bin\gcc --version
        where C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw32\bin\gcc

    - name: Build 32-bit DLL
      shell: cmd
      run: |
        C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw32\bin\gcc -shared -o ToText_32.dll -m32 ToText.c

    - name: Upload DLL
      uses: actions/upload-artifact@v2
      with:
        name: dll-files
        path: ./ToText_32.dll
