name: Build DLL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install MinGW
      run: |
        choco install mingw -y
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -Append -FilePath $env:GITHUB_PATH
    

    - name: Build 32-bit DLL
      shell: cmd
      run: |
        gcc -shared -o -static -O3 ToText_32.dll -m32 ToText.c

    - name: Upload DLL
      uses: actions/upload-artifact@v2
      with:
        name: dll-files
        path: ./ToText_32.dll
