name: Build 32-bit Windows Dynamic Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MinGW
      run: |
        choco install mingw
        Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
        refreshenv

    - name: Build 32-bit dynamic library
      run: |
        gcc -m32 -shared -o ToText.dll -Wl,--out-implib,libToText.a ToText.c

    - name: Upload built library
      uses: actions/upload-artifact@v2
      with:
        name: ToText
        path: |
          ToText.dll
          libToText.a
