name: Build 32-bit and 64-bit Windows Dynamic Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install mingw-w64 for cross-compilation
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64

    - name: Build 32-bit dynamic library
      run: |
        i686-w64-mingw32-gcc -shared -static -O3 -o ToText32.dll -Wl,--out-implib,libToText32.a ToText.c

    - name: Build 64-bit dynamic library
      run: |
        x86_64-w64-mingw32-gcc -shared -static -O3 -o ToText64.dll -Wl,--out-implib,libToText64.a ToText.c

    - name: Upload built libraries
      uses: actions/upload-artifact@v2
      with:
        name: ToText
        path: |
          ToText32.dll
          libToText32.a
          ToText64.dll
          libToText64.a
