name: Build DLL from C file

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '4.6.2'

    - name: Install necessary packages
      run: sudo apt-get install -y mingw-w64

    - name: Build DLL
      run: |
        # Compile the C file to object file targeting Windows
        x86_64-w64-mingw32-gcc -c -o totext.o totext.c
        # Create the DLL file targeting Windows
        x86_64-w64-mingw32-gcc -shared -o totext.dll totext.o
        mkdir -p MyLibrary/out
        mv totext.dll MyLibrary/out/

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-windows-dll
        path: MyLibrary/out
